// File: src/models/Hire.js

import mongoose from 'mongoose';

const HireSchema = new mongoose.Schema({
  organizationId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Organization',
    required: true
  },
  hireId: {
    type: String,
    unique: true
    // NOT required - will be auto-generated by pre-save hook
  },
  passengerName: {
    type: String,
    required: [true, 'Passenger name is required'],
    trim: true
  },
  pickupLocation: {
    type: String,
    required: [true, 'Pickup location is required'],
    trim: true
  },
  dropLocation: {
    type: String,
    required: [true, 'Drop location is required'],
    trim: true
  },
  dateTime: {
    type: Date,
    required: [true, 'Date and time is required']
  },
  numberOfPassengers: {
    type: Number,
    required: [true, 'Number of passengers is required'],
    min: 1
  },
  hirePrice: {
    type: Number,
    required: [true, 'Hire price is required'],
    min: 0
  },
  specialRequirements: {
    type: String,
    trim: true
  },
  vehicleId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Vehicle'
  },
  vehicleType: {
    type: String,
    enum: ['Car', 'Van', 'SUV', 'Bus', 'Other']
  },
  assignmentType: {
    type: String,
    enum: ['auto', 'manual'],
    default: 'auto'
  },
  status: {
    type: String,
    enum: ['active', 'pending', 'accepted', 'in_progress', 'completed', 'cancelled'],
    default: 'active'
  },
  tripProgress: {
    acceptedAt: Date,
    acceptedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    },
    startedAt: Date,
    completedAt: Date,
    driverNotes: String
  },
  commission: {
    managerCommission: {
      type: Number,
      default: 0
    },
    systemCommission: {
      type: Number,
      default: 0
    },
    driverEarnings: {
      type: Number,
      default: 0
    }
  },
  cancellationReason: {
    type: String,
    trim: true
  },
  completedBy: {
    driverName: String,
    driverId: String,
    completedAt: Date
  },
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  }
}, {
  timestamps: true
});

// Auto-generate hireId before saving
HireSchema.pre('save', async function() {
  if (!this.hireId) {
    const count = await mongoose.model('Hire').countDocuments({ 
      organizationId: this.organizationId 
    });
    this.hireId = `HF-${String(count + 1).padStart(4, '0')}`;
  }
});

// Indexes for faster queries
HireSchema.index({ organizationId: 1, status: 1 });
HireSchema.index({ organizationId: 1, dateTime: -1 });

export default mongoose.models.Hire || mongoose.model('Hire', HireSchema);